sonar.projectKey=ant-cg_ProyectoWeb-CI-CD
sonar.organization=ant-cg

sonar.projectName=ProyectoWeb-CI-CD

sonar.sources=backend

sonar.sourceEncoding=UTF-8

sonar.exclusions=backend/node_modules/**,backend/report.html