name: CI Pipeline

on:
  push:
    branches:
      - feature/ci-cd
      - main

  pull_request:
    branches:
      - main


jobs:

  backend-tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend


    steps:

      # Descargar código
      - name: Descargar repositorio
        uses: actions/checkout@v4


      # Configurar Node
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      # Instalar dependencias
      - name: Instalar dependencias
        run: npm install


      # Ejecutar Jest
      - name: Ejecutar pruebas unitarias
        run: npm test


      # Levantar API
      - name: Levantar backend
        run: |
          npm start &
          sleep 10
          

      # Instalar k6
      - name: Instalar k6
        uses: grafana/setup-k6-action@v1


      # Ejecutar pruebas API
      - name: Ejecutar pruebas API con k6
        run: |
          k6 run performance/performance-test.js


      # Ejecutar Análisis de SonarQube 
      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}